server:
  port: 8900

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery-container:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
